#!/bin/sh

# Start docker
echo "Starting docker"
docker compose up --build --detach

if command -v netstat &> /dev/null
then
  while ! netstat -tna | grep 'LISTEN' | grep -q '.8090'; do
    echo "Waiting for Postgres..."
    sleep 2 # time in seconds, tune it as needed
  done
else
  while ! ss -tulpn | grep LISTEN | grep :8090; do
    echo "Waiting for Postgres..."
    sleep 2
  done
fi

sleep 2

echo "Postgres is ready"

docker compose run --rm postgres env PGPASSWORD="URZy--P9qprxx7p7Ly21EcDGG7izBrhU" psql -h postgres -U postgres -d dawn < generated/tables-serverpod.pgsql

echo "Stopping docker"
docker compose stop
